export const categoryList = [
  {
    id: 1,
    value: 'house',
    label: '🏡 House',
  },
  {
    id: 2,
    value: 'bungalow',
    label: '🏰 Bungalow',
  },
  {
    id: 3,
    value: 'resort',
    label: '💒 Resort',
  },
  {
    id: 4,
    value: 'hotel',
    label: '🏨 Hotel',
  },
]

export const ratingList = [
  {
    id: 1,
    value: '1',
    label: '1🌟',
  },
  {
    id: 2,
    value: '2',
    label: '2🌟',
  },
  {
    id: 3,
    value: '3',
    label: '3🌟',
  },
  {
    id: 4,
    value: '4',
    label: '4🌟',
  },
  {
    id: 5,
    value: '5',
    label: '5🌟',
  },
]

export const dataList = [
  {
    id: 1,
    title: 'lounge resort',
    category: 'resort',
    rating: 5,
    price: 1200,
    space: 205.2,
    rooms: 2,
    beds: 1,
    bathrooms: 1,
    coverSrc: '/images/places/ameri.jpg',
  },
  {
    id: 2,
    title: 'Faulkner Avenue',
    category: 'bungalow',
    rating: 4.5,
    price: 4550,
    space: 168.9,
    rooms: 3,
    beds: 2,
    bathrooms: 1,
    coverSrc: '/images/places/italian.webp',
  },
  {
    id: 3,
    title: 'Palm Harbor',
    category: 'bungalow',
    rating: 4,
    space: 145.7,
    rooms: 3,
    beds: 1,
    bathrooms: 2,
    price: 2095,
    coverSrc: '/images/places/italian.webp',
  },
  {
    id: 4,
    title: 'JW mariott',
    category: 'hotel',
    rating: 4,
    space: 300,
    rooms: 2,
    beds: 2,
    bathrooms: 1,
    price: 5000,
    coverSrc: '/images/places/italian.webp',
  },
  {
    id: 5,
    title: 'beverly springfield',
    category: 'house',
    rating: 3.5,
    space: 405.2,
    rooms: 3,
    beds: 2,
    bathrooms: 2,
    price: 5000,
    coverSrc: '/images/places/italian.webp',
  },
  {
    id: 6,
    title: "The ahmed's",
    category: 'house',
    rating: 5,
    space: 1000,
    rooms: 4,
    beds: 3,
    bathrooms: 3,
    price: 3500,
    coverSrc: '/images/places/italian.webp',
  },
]
